apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ged75ag3x-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ged75ag3x-nodejs 
  name: ged75ag3x-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ged75ag3x-nodejs
    weight: 100 
