apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ged75ag3x-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ged75ag3x-nodejs 
  name: ged75ag3x-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ged75ag3x-nodejs 
